# Generated by Django 5.0.3 on 2024-03-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_image',
            field=models.FileField(default='default_img.png', upload_to='media'),
        ),
    ]
