# Generated by Django 5.0.3 on 2024-03-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0004_users_user_status_alter_users_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.FileField(default='default_img.jpg', upload_to='profile/'),
        ),
    ]
