# Generated by Django 5.0.3 on 2024-03-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0005_alter_users_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SchoolAdmin.users'),
        ),
    ]
